### ISSUE TITLE
Add support for ES algorithms

### ISSUE THREAD

**Issue by lindelius** [lindelius/php-jwt#1]
The library is currently missing support for the recommended elliptic curve algorithms ES256, ES384, and ES512.

**Comment by peter279k** [comment]
Hi @lindelius, I have some questions about this issue.

- Do we need to implement this feature for this package?
- Can we include the `ES` libraries to support this feature?

Thanks.

**Comment by lindelius** [comment]
Hi @peter279k,

Thank you for showing interest in the library.

The ideal contribution would implement the missing algorithms in a similar fashion to https://github.com/lcobucci/jwt and https://github.com/web-token/jwt-framework, and without requiring any external libraries or creating any additional classes.

**Comment by peter279k** [comment]
Hi @lindelius, thank you for your reply.

After looking at the repos that you mention, I think they use the additional `ECC` package to complete this featutre.

The [lcobucci/jwt](https://github.com/lcobucci/jwt/commit/f787525876a4481d73c403f2728b4b2d373516ae) uses the [phpecc ](https://github.com/phpecc/phpecc)library.

And the [web-token/jwt-framework](https://github.com/web-token/jwt-framework/tree/v1.2/src/Ecc) uses the sub repo in this main repo.

You should check that.

**Comment by lindelius** [comment]
@peter279k, Thank you for taking the time to dig around.

I have done some thinking and while I'm still against adding any external libraries (extensions would be OK) I did end up reworking the algorithm support to make it more extendable. The updated code is in the `extendable-algorithm-support` branch, and if you have the time I would appreciate your input.

I haven't started on any EC implementations, but the rework should make adding this easier. The idea is to add the necessary traits, and, if necessary, additional classes, as well.

**Comment by peter279k** [comment]
@lindelius, thank you for your reply.

After looking at the `extendable-algorithm-support` branch, it seems that you want to create the `ES256`, `ES384` and `ES512` classes without any `php-ecc` package/dependencies.

I think it's fine to use this approach you mention to complete this feature.

But I think we need to keep this `ES` functionality simple and lightweight.

I will refer that branch and create the PR for this issue and let you review that.

Thanks :).

**Comment by peter279k** [comment]
@lindelius, I also refer this `psecio/jwt` [repo](https://github.com/psecio/jwt/tree/master/src/Psecio/Jwt/HashMethod) to implement this `ES` algorithm support.

Please check that, thanks.
