### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by newtovaux** [lindelius/php-jwt#14]
Currently, composer fails to install if PHP > 8:

```
Problem 1
    - Root composer.json requires lindelius/php-jwt ^0.9 -> satisfiable by lindelius/php-jwt[0.9].
    - lindelius/php-jwt 0.9 requires php ^7.2 -> your php version (8.0.2) does not satisfy that requirement.
```

**Comment by lindelius** [comment]
Hi @newtovaux 

Try again with the new `0.9.1` release and let me know if that works for you :)

**Comment by newtovaux** [comment]
Thanks for doing that release @lindelius composer now happy on PHP 8.0 :)
