### ISSUE TITLE
How do I get the $decodedJwt id?

### ISSUE THREAD

**Issue by noloop** [lindelius/php-jwt#8]
How do I get the $decodedJwt id?

In the firebase library, I do so:

`$user->id = $decoded->data->id;`

When I try `$decodedJwt->sub` I get null. When I check the `$decodedJwt` object, it is empty.

**Comment by noloop** [comment]
I had misunderstood it, and was calling an empty $ jwt object instead of grabbing the decode. I apologize.

**Comment by lindelius** [comment]
No worries!
Let me know if you have any further questions :)
